export const DELETE_SERVICE = 'DELETE_SERVICE';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const ADD_SERVICE = 'ADD_SERVICE';
export const GET_SERVICE_LOADING = 'GET_SERVICE_LOADING';
export const GET_SERVICE_SUCCESS = 'GET_SERVICE_SUCCESS';
